同步到最新版本

diff --git a/tools/easzup b/tools/easzup
--- a/tools/easzup
+++ b/tools/easzup
@@ -14,24 +14,33 @@ set -o errexit
 #set -o xtrace
 
 # default version, can be overridden by cmd line options
-export DOCKER_VER=18.09.7
-export KUBEASZ_VER=2.0.1
-export K8S_BIN_VER=v1.14.3
+export DOCKER_VER=18.09.8
+export KUBEASZ_VER=2.0.3
+export K8S_BIN_VER=v1.15.2
 export EXT_BIN_VER=0.3.0
-export SYS_PKG_VER=0.2.1
+export SYS_PKG_VER=0.3.2
 
 function install_docker() {
   # check if a container runtime is already installed
   systemctl status docker|grep Active|grep -q running && { echo "[WARN] docker is already running."; return 0; }
   systemctl status containerd|grep Active|grep -q running && { echo "[ERROR] containerd is running, unsupported."; exit 1; }
+  
+  if [[ "$REGISTRY_MIRROR" == CN ]];then
+    DOCKER_URL="https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/static/stable/x86_64/docker-${DOCKER_VER}.tgz"
+  else
+    DOCKER_URL="https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_VER}.tgz"
+  fi
 
-  DOCKER_URL=https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/static/stable/x86_64/docker-${DOCKER_VER}.tgz
   mkdir -p /opt/kube/bin /etc/docker /etc/ansible/down
   if [[ -f "/etc/ansible/down/docker-${DOCKER_VER}.tgz" ]];then
     echo "[INFO] docker binaries already existed"
   else
     echo -e "[INFO] \033[33mdownloading docker binaries\033[0m $DOCKER_VER"
-    curl -C- -O --retry 3 "$DOCKER_URL" || { echo "[ERROR] downloading docker failed"; exit 1; }
+    if [[ -e /usr/bin/curl ]];then
+      curl -C- -O --retry 3 "$DOCKER_URL" || { echo "[ERROR] downloading docker failed"; exit 1; }
+    else
+      wget -c "$DOCKER_URL" || { echo "[ERROR] downloading docker failed"; exit 1; }
+    fi
     mv ./docker-${DOCKER_VER}.tgz /etc/ansible/down
   fi
 
@@ -60,8 +69,11 @@ KillMode=process
 WantedBy=multi-user.target
 EOF
 
+  # configuration for dockerd
   echo "[INFO] generate docker config file"
-  cat > /etc/docker/daemon.json << EOF
+  if [[ "$REGISTRY_MIRROR" == CN ]];then
+    echo "[INFO] prepare register mirror for $REGISTRY_MIRROR"
+    cat > /etc/docker/daemon.json << EOF
 {
   "registry-mirrors": [
     "https://dockerhub.azk8s.cn",
@@ -78,6 +90,21 @@ EOF
   "data-root": "/var/lib/docker"
 }
 EOF
+  else
+    echo "[INFO] standard config without registry mirrors"
+    cat > /etc/docker/daemon.json << EOF
+{
+  "max-concurrent-downloads": 10,
+  "log-driver": "json-file",
+  "log-level": "warn",
+  "log-opts": {
+    "max-size": "10m",
+    "max-file": "3"
+    },
+  "data-root": "/var/lib/docker"
+}
+EOF
+  fi
 
   if [[ -e /etc/centos-release || -e /etc/redhat-release ]]; then
     echo "[INFO] turn off selinux in CentOS/Redhat"
@@ -254,7 +281,7 @@ function start_kubeasz_docker() {
       --volume /root/.ssh/id_rsa:/root/.ssh/id_rsa:ro \
       --volume /root/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub:ro \
       --volume /root/.ssh/known_hosts:/root/.ssh/known_hosts:ro \
-      easzlab/kubeasz:${KUBEASZ_VER}
+      easzlab/kubeasz:${KUBEASZ_VER} sleep 36000
 }
 
 function clean_container() {
@@ -272,6 +299,7 @@ Usage: easzup [options] [args]
     -d <ver>   set docker-ce version, default "$DOCKER_VER"
     -e <ver>   set kubeasz-ext-bin version, default "$EXT_BIN_VER"
     -k <ver>   set kubeasz-k8s-bin version, default "$K8S_BIN_VER"
+    -m <str>   set docker registry mirrors, default "CN"(used in Mainland,China)
     -p <ver>   set kubeasz-sys-pkg version, default "$SYS_PKG_VER"
     -z <ver>   set kubeasz version, default "$KUBEASZ_VER"
   
@@ -288,8 +316,9 @@ function main() {
   
   [[ "$#" -eq 0 ]] && { usage >&2; exit 1; }
   
+  export REGISTRY_MIRROR="CN"
   ACTION=""
-  while getopts "CDSd:e:k:p:z:" OPTION; do
+  while getopts "CDSd:e:k:m:p:z:" OPTION; do
       case "$OPTION" in
         C)
           ACTION="clean_container"
@@ -309,8 +338,11 @@ function main() {
         k)
           export K8S_BIN_VER="$OPTARG"
           ;;
+        m)
+          export REGISTRY_MIRROR="$OPTARG"
+          ;;
         p)
-          export K8S_SYS_PKG="$OPTARG"
+          export SYS_PKG_VER="$OPTARG"
           ;;
         z)
           export KUBEASZ_VER="$OPTARG"
